
[tools]
bat = "latest"
bat-extras = "latest"
"cargo:lq" = "latest"
fd = "latest"
gemini = "latest"
jqp = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
mkcert = "latest"
neovim = "latest"
node = "latest"
python = "3.11.14"
ruby = "latest"
sqlite = "latest"
rust = "latest"
terraform = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
