return {
  ensure_installed = {
    "bash-language-server",
    "css-lsp",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "html-lsp",
    "java-language-server",
    "kotlin-language-server",
    "lua-language-server",
    "ruby-lsp",
    -- "solargraph",
    -- "spectral-language-server",
    "sqlls",
    "standardrb",
    "terraform-ls",
    "vim-language-server",
    -- "bash-debug-adapter",
    -- "kotlin-debug-adapter",
    -- "rubocop",
    -- "rust-analyzer",
    -- "stylua",
  },
}
